/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as governorSol from "./Governor.sol";
export type { governorSol };
export type { NewNFTToken } from "./NewNFTToken";
export type { OldNFTToken } from "./OldNFTToken";
export type { Timelock } from "./Timelock";
