/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as draftErc721VotesSol from "./draft-ERC721Votes.sol";
export type { draftErc721VotesSol };
export type { IERC721Metadata } from "./IERC721Metadata";
