/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as governorSol from "./Governor.sol";
export { NewNFTToken__factory } from "./NewNFTToken__factory";
export { OldNFTToken__factory } from "./OldNFTToken__factory";
export { Timelock__factory } from "./Timelock__factory";
