/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Governor } from "./Governor";
export type { NewToken } from "./NewToken";
export type { OldToken } from "./OldToken";
export type { Timelock } from "./Timelock";
