/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Governor__factory } from "./Governor__factory";
export { NewToken__factory } from "./NewToken__factory";
export { OldToken__factory } from "./OldToken__factory";
export { Timelock__factory } from "./Timelock__factory";
